name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # or 'adopt'
        java-version: '17'

    # Build the JAR file with Maven
    - name: Build with Maven
      run: mvn package

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
