name: Java CI with Maven and Docker Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      TIMESTAMP: ${{ github.run_id }}  # Use a fixed timestamp or unique identifier

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the JAR file with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image and tag it
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag freepizza2024/qa-backend:latest
          docker tag freepizza2024/qa-backend:latest freepizza2024/qa-backend:${{ env.TIMESTAMP }}

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: |
          docker push freepizza2024/qa-backend:latest
          docker push freepizza2024/qa-backend:${{ env.TIMESTAMP }}
