name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Use 'temurin' for OpenJDK builds

    # Build the JAR file with Maven
    - name: Build with Maven
      run: mvn package

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build the Docker image and tag it
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag freepizza2024/qa-backend:latest
        docker tag freepizza2024/qa-backend:latest freepizza2024/qa-backend:$(date +%s)

    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: |
        docker push freepizza2024/qa-backend:latest
        docker push freepizza2024/qa-backend:$(date +%s)
